//router部分
app.config(function($stateProvider,$urlRouterProvider){
	$stateProvider.state('index',{
		url:'/index',
		views:{
			'':{templateUrl:'tpl/main.html'}
		},
        //controller:'mainCtrl'
	})
	.state('nanwang',{
		url:'/nanwang',
		views:{
			'':{templateUrl:'tpl/nanwang.html'},
            "topbar@nanwang":{templateUrl:'tpl/topbar1.html'},
            "sidebar@nanwang":{templateUrl:'tpl/nanwang/sidebar1.html'},
            "main@nanwang":{templateUrl:'tpl/nanwangbegin.html'}
		}
	}).state('pointstone',{
		url:'/pointstone',
		views:{
			'':{templateUrl:'tpl/pointstone.html'}
		}
	}).state('nanwang.list',{
        url:'/list',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/list.html'
            }
        }
    })
    .state('nanwang.school',{
        url:'/school',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/school.html'
            }
        }
    }).state('nanwang.map',{
        url:'/map',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/map.html'
            }
        }
    }).state('nanwang.wholeschool',{
        url:'/wholeschool',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/wholeschool.html'
            }
        }
    }).state('nanwang.trans',{
        url:'/trans',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/trans.html'
            }
        }
    }).state('nanwang.process',{
        url:'/process',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/process.html'
            }
        }
    }).state('nanwang.loan',{
        url:'/loan',
        views:{
            'main@nanwang':{
                templateUrl:'tpl/nanwang/loan.html'
            }
        }
    }).state('donglin',{
        url:'/donglin',
        views:{
            '':{templateUrl:'tpl/donglin.html'},
            "topbar@donglin":{templateUrl:'tpl/topbar2.html'},
            "main@donglin":{templateUrl:'tpl/donglinlife.html'},
            "sidebar@donglin":{templateUrl:'tpl/donglin/sidebar2.html'},
        }
    }).state('donglin.army',{
        url:'/army',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/army.html'
            }
        }
    }).state('donglin.dor',{
        url:'/dor',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/dor.html'
            }
        }
    }).state('donglin.web',{
        url:'/web',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/web.html'
            }
        }
    }).state('donglin.food',{
        url:'/food',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/food.html'
            }
        }
    }).state('donglin.entertain',{
        url:'/entertain',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/entertain.html'
            }
        }
    }).state('donglin.life_trans',{
        url:'/life_trans',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/life_trans.html'
            }
        }
    }).state('donglin.party',{
        url:'/party',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/party.html'
            }
        }
    }).state('donglin.partime',{
        url:'/partime',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/partime.html'
            }
        }
    }).state('donglin.hobby',{
        url:'/hobby',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/hobby.html'
            }
        }
    }).state('donglin.union',{
        url:'/union',
        views:{
            'main@donglin':{
                templateUrl:'tpl/donglin/union.html'
            }
        }
    }).state('gold',{
        url:'/gold',
        views:{
            '':{templateUrl:'tpl/gold.html'},
            "topbar@gold":{templateUrl:'tpl/topbar3.html'},
            "main@gold":{templateUrl:'tpl/nanwangbegin.html'},
            "sidebar@gold":{templateUrl:'tpl/gold/sidebar3.html'},
        }
    }).state('gold.build',{
        url:'/build',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/build.html'
            }
        }
    }).state('gold.lib',{
        url:'/lib',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/lib.html'
            }
        }
    }).state('gold.study',{
        url:'/study',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/study.html'
            }
        }
    }).state('gold.exam',{
        url:'/exam',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/exam.html'
            }
        }
    }).state('gold.major_ch',{
        url:'/major_ch',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/major_ch.html'
            }
        }
    }).state('gold.tw_deg',{
        url:'/tw_deg',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/tw_deg.html'
            }
        }
    }).state('gold.rubbage',{
        url:'/rubbage',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/rubbage.html'
            }
        }
    }).state('gold.gradu',{
        url:'/gradu',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/gradu.html'
            }
        }
    }).state('gold.foreign',{
        url:'/foreign',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/foreign.html'
            }
        }
    }).state('gold.job',{
        url:'/job',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/job.html'
            }
        }
    }).state('gold.stu_work',{
        url:'/stu_work',
        views:{
            'main@gold':{
                templateUrl:'tpl/gold/stu_work.html'
            }
        }
    })

    $urlRouterProvider.otherwise('/index');

})